Shape FFI wrappers
jbuckmccready/cavalier_contours pull request #47
Opened 2024-12-27 05:58 UTC by bdurbrow

Added FFI wrappers to shape methods for creating, offsetting, and getting the results.

2025-01-03 18:36 UTC, jbuckmccready requested changes
I suggested some minor doc comment changes. It would be nice to have basic tests for the new functions, there are already tests for the other parts of the c ffi in `cavalier_contours_ffi/tests/test_pline.rs`. If you don't have time to add them I'll try to find some time to add them, please let me know what you can do it should be simple enough following the existing test structuring.

I wasn't sure on the API of a "Shape" type (I just got it into the code to have the algorithm out of my mind) but I think it's good to have something available/working for immediate practical use, thanks for the PR!

2025-01-03 18:36 UTC, jbuckmccready commented on cavalier_contours_ffi/src/lib.rs
> +/// `capacity` is the number of plines to pre=allocate space for. May be zero.
```suggestion
/// `capacity` is the number of plines to pre-allocate space for. May be zero.
```

2025-01-03 18:36 UTC, jbuckmccready commented on cavalier_contours_ffi/src/lib.rs
> +/// Append a [cavc_pline] to the end of a [cavc_plinelist].
```suggestion
/// Append a [cavc_pline] to the end of a [cavc_plinelist], the [cavc_plinelist] takes ownership of the polyline.
```

2025-01-04 05:10 UTC, bdurbrow commented
I should be able to cook something together for tests.

2025-01-08 15:02 UTC, closed without merging